---
title: "03-04ROC_PRC_Training-Test"
output: html_document
date: "2024-10-19"
---

**导入包**：
```{r}
library(ggplot2);
library(precrec);
library(pROC);
library(patchwork);
library(ggpubr);
library(cowplot);
```
**基础的数据分析和图**（作者提供的代码）：包括画ROC和PRC曲线，计算AUC值等
```{r}
# 画ROC和PRC曲线
draw_ROC_PRC <- function(data, cancer_type = ""){
  scores1 <- join_scores(data$RF16_prob, data$RF11_prob, data$TMB);
  msmdat <- mmdata(scores1, data$Response);
  msmdat2 <- mmdata(
    scores1, data$Response, 
    modnames = c("RF16", "RF11", "TMB")
  );
  mscurves <- evalmod(msmdat2);
  all_pic <- autoplot(mscurves);  # 原始图
  # 给图加标题（癌症种类）
  p1 <- all_pic[[1]] + theme(legend.position = "none");
  p2 <- all_pic[[2]];
  all_pic_new <- (p1 + p2) + 
    plot_annotation(title = cancer_type) &
    theme(plot.title = element_text(hjust = 0.5));
  print(all_pic_new);
  # 分界线、曲线具体数值
  if(cancer_type!="") cancer_type <- paste0(" ", cancer_type, " ");
  print(paste0("|----------", cancer_type, "----------|"));
  print(mscurves);
  print(paste0("|----------", paste(replicate(nchar(cancer_type), "-"), collapse = ""), "----------|"));
}
# 计算最佳阈值
get_optimal_threshold <- function(data, type = "RF16"){
  if(type == "RF16"){
    prob_roc <- roc(data$Response, data$RF16_prob);
  } else {
    prob_roc <- roc(data$Response, data$RF11_prob);
  }
  par(pty = "s");
  plot.roc(
    prob_roc, 
    col = "red", 
    print.auc = TRUE, print.auc.adj = c(2,-12),
    max.auc.polygon = TRUE, 
    print.thres = TRUE, print.thres.pch = 19, print.thres.col = "red", print.thres.adj = c(0.3,-1.2),
    auc.polygon = TRUE, auc.polygon.col = "#D1F2EB",
    legacy.axes = TRUE
  );
  legend("bottomright", legend = c(type), col = c("red"), lwd = 2, bty = "n");
  # title(type);
  pan_threshold <- ci.thresholds(prob_roc, thresholds = "best");
  return(pan_threshold);
}
# 将最佳阈值写入
write_optimal_threshold <- function(pan_threshold, cancer_type, file_path){
  cat(paste(cancer_type, "Threshold", sep = " "), file = file_path, append = TRUE);
  capture.output(pan_threshold, file = file_path, append = TRUE);
  # 注：capture.output函数必须在终端中运行才可正常工作，在rmd中运行只能输出第一行内容
}
# 训练组
training_func <- function(data, cancer_type = "Pan-cancer", file_path = "data/Pan_Thresholds.txt", type = "RF16"){
  draw_ROC_PRC(data, cancer_type);
  write_optimal_threshold(
    get_optimal_threshold(data, type = type),
    cancer_type,
    file_path
  );
}
```
**训练组**：（如果想得到完整的txt文件，就在终端中运行该段代码，因为`capture.output`函数必须在终端中运行才可正常工作）
```{r}
data <- read.table('../pycharm/data/Training_RF_Prob.txt', header = T, sep = '\t');
# 泛癌
training_func(data);
training_func(data, "Pan-cancer", "data/Pan_Thresholds_RF11.txt", "RF11");
# Melanoma
data_Melanoma <- data[grep("0", data$Cancer_Type), ];
training_func(data_Melanoma, "Melanoma", "data/Thresholds.txt");
training_func(data_Melanoma, "Melanoma", "data/Thresholds_RF11.txt", "RF11");
# NSCLC
data_NSCLC <- data[grep("1", data$Cancer_Type), ];
training_func(data_NSCLC, "NSCLC", "data/Thresholds.txt");
training_func(data_NSCLC, "NSCLC", "data/Thresholds_RF11.txt", "RF11");
# 其它
data_Others <- data[grep("2", data$Cancer_Type), ];
training_func(data_Others, "Others", "data/Thresholds.txt");
training_func(data_Others, "Others", "data/Thresholds_RF11.txt", "RF11");
```
**验证组**：
```{r}
data <- read.table('../pycharm/data/Test_RF_Prob.txt', header = T, sep = '\t');
# 泛癌
draw_ROC_PRC(data, "Pan-cancer");
# Melanoma
data_Melanoma <- data[grep("0", data$Cancer_Type), ];
draw_ROC_PRC(data_Melanoma, "Melanoma");
# NSCLC
data_NSCLC <- data[grep("1", data$Cancer_Type), ];
draw_ROC_PRC(data_NSCLC, "NSCLC");
# 其它
data_Others <- data[grep("2", data$Cancer_Type), ];
draw_ROC_PRC(data_Others, "Others");
```
**画图前的数据处理**：主要是把数据根据癌症类型分组，将`response`从0/1改成NR/R，将`Cancer_Type`从0/1/2改成具体的癌症名称
```{r}
# 数据读取
data <- read.table('../pycharm/data/Test_RF_Prob.txt', header = T, sep = '\t');  # 验证组数据
cancer_type <- c("Pan-cancer", "Melanoma", "NSCLC","Others");  # 癌症类型
data1_p <- c();  # 两组数据在小提琴图中的p值
data2_p <- c();
# 泛癌：先复制一遍所有的数据，作为泛癌组存入data_all，之后再添加各种癌症的样本，最后data_all长度是data的两倍。目的是让Cancer_Type列有不同的值，以便画小提琴图
data_pan <- data;
data_pan$Cancer_Type <- "Pan-cancer";
data1_p <- append(data1_p, wilcox.test(RF16_prob ~ Response, data_pan)$p.value);
data2_p <- append(data2_p, wilcox.test(TMB ~ Response, data_pan)$p.value);
data_all <- data_pan;
# Melanoma
data_Melanoma <- data[grep("0", data$Cancer_Type), ];
data_Melanoma$Cancer_Type <- "Melanoma";
data1_p <- append(data1_p, wilcox.test(RF16_prob ~ Response, data_Melanoma)$p.value);
data2_p <- append(data2_p, wilcox.test(TMB ~ Response, data_Melanoma)$p.value);
data_all <- rbind(data_all, data_Melanoma);
# NSCLC
data_NSCLC <- data[grep("1", data$Cancer_Type), ];
data_NSCLC$Cancer_Type <- "NSCLC";
data1_p <- append(data1_p, wilcox.test(RF16_prob ~ Response, data_NSCLC)$p.value);
data2_p <- append(data2_p, wilcox.test(TMB ~ Response, data_NSCLC)$p.value);
data_all <- rbind(data_all, data_NSCLC);
# Others
data_Others <- data[grep("2", data$Cancer_Type), ];
data_Others$Cancer_Type <- "Others";
data1_p <- append(data1_p, wilcox.test(RF16_prob ~ Response, data_Others)$p.value);
data2_p <- append(data2_p, wilcox.test(TMB ~ Response, data_Others)$p.value);
data_all <- rbind(data_all, data_Others);
```
**画ROC曲线**：
```{r}
draw_roc <- function(data, cancer_type){
  # 计算AUC值
  auc_list <- c(
    roc(data$Response ~ data$RF16_prob)[["auc"]],
    roc(data$Response ~ data$RF11_prob)[["auc"]],
    roc(data$Response ~ data$TMB)[["auc"]]
  );
  auc_list <- sprintf("%0.2f", auc_list);  # 保留两位小数
  auc_text <- c(  # AUC在图中的标注文本
    paste0("RF16   (AUC: ", auc_list[1], ")"),
    paste0("RF11   (AUC: ", auc_list[2], ")"),
    paste0("TMB    (AUC: ", auc_list[3], ")")
  );
  # 画roc图
  msmdat <- mmdata(
    join_scores(data$RF16_prob, data$RF11_prob, data$TMB), 
    data$Response,
    modnames = c("RF16", "RF11", "TMB")
  );
  roc_pic <- autoplot(evalmod(msmdat))[[1]];  # 原始roc图
  # 修改图
  roc_pic_new <- roc_pic +
    geom_line(linewidth = line_width) +  # 设置线条宽度
    ggtitle("") +  # 去掉标题
    labs(
      x = "", y = "",  # 去掉xy轴标签
      color = cancer_type  # 修改图例标题
    ) +
    scale_color_manual(
      values = c("#E51818", "#1AA74A", "#245080"),  # 线条颜色
      labels = auc_text  # 图例的标签内容
    ) +
    theme(  # 隐藏背景色
      panel.background = element_rect(fill = "transparent", colour = NA),
      plot.background = element_rect(fill = "transparent", colour = NA),
    ) +
    theme(  # 图例
      legend.position = c(legend_x, legend_y),  # 位置
      legend.title = element_text(hjust = 1, size = font_size),  # 标题（hjust设置右对齐）
      legend.key.size = unit(legend_key_size, 'pt'),  # 图例大小
      legend.text = element_text(size = font_size),  # 图例文字字号
      legend.key.spacing.y = unit(legend_key_distance, 'lines'),  # 图例各项上下间距
      legend.background = element_blank(),  # 去掉图例背景色
      legend.key = element_blank()  # 去掉图例背景色
    ) +
    theme(  # xy轴刻度标签字号
      axis.text = element_text(size = font_size),
    );
  return(roc_pic_new);
}
# 画图参数
font_size <- 18;  # 图例和xy轴标签字号
legend_x <- 0.6;  # 图例x坐标
legend_y <- 0.22;  # 图例y坐标
line_width <- 1.1;  # 折线粗细
legend_key_distance <- -1;  # 图例项间距，数越小越近
legend_key_size <- 40;  # 图例项大小
# 组合图
p <- plot_grid(
  draw_roc(data_pan, cancer_type[1]),
  draw_roc(data_Melanoma, cancer_type[2]),
  draw_roc(data_NSCLC, cancer_type[3]),
  draw_roc(data_Others, cancer_type[4]),
  ncol = 4, 
  align = "h"  # y轴对齐
);
res_p <- annotate_figure(  # 添加xy轴标签
  p,
  bottom = text_grob("1 - specificity", hjust = 0.5, size = font_size, vjust = -2, x = 0.52),  # vjust越小越往上
  left = text_grob("Sensitivity", size = font_size, rot = 90)
);
# 保存图片
pdf(file = "plot/ROC.pdf", width = 20, height = 6);
print(res_p);
dev.off();
```
**画小提琴图**：
```{r}
# RF16数据
data1 <- data.frame(
  response = ifelse(data_all$Response==0, "NR", "R"),
  cancer_type = factor(data_all$Cancer_Type, levels = cancer_type), 
  rf16 = data_all$RF16_prob
);
# TMB数据
data2 <- data.frame(
  response = ifelse(data_all$Response==0, "NR", "R"),
  cancer_type = factor(data_all$Cancer_Type, levels = cancer_type), 
  tmb = log2(data_all$TMB+1)
);
# 画RF16
p1 <- ggplot(
  data1, 
  aes(x = cancer_type, y = rf16), 
) +
  geom_violin(  # 小提琴图
    aes(fill = response), 
    trim = FALSE,
    width = 1.1,
    position = position_dodge(0.9)  # 指定位置
  ) +
  scale_fill_manual(values = c("#01B1BC", "#E8B900")) +
  scale_color_manual(values = c("black", "black")) +
  geom_boxplot(  # 箱型图
    aes(color = response),
    width = 0.2,
    outlier.size = 3,  # 离群值点的大小
    fatten = 5,  # 中值线的粗细
    position = position_dodge(0.9),  # 使箱型图位于小提琴图的中间
    show_guide = FALSE  # 不显示箱型图的图例，只显示小提琴图的图例（隐藏图例中箱型图的形状）
  ) +
  labs(x = "Cancer type", y = "Response probability (RF16)") +  # xy轴标签
  scale_y_continuous(  # y轴刻度
      breaks = c(0, 0.25, 0.5, 0.75),
      labels = c("0.00", "0.25", "0.50", "0.75")
  ) +
  theme(  # 隐藏网格线和背景色
    panel.grid.major = element_line(colour = NA),
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.grid.minor = element_blank()
  ) +
  theme(  # 隐藏上侧/右侧边框线
    panel.border = element_blank(), 
    axis.line = element_line()
  ) +
  theme(  # 隐藏x轴刻度
    axis.ticks.x=element_blank()
  ) +
  theme(  # 图例
    legend.position = c(1, 0.5),  # 图例位置
    legend.title = element_blank(),  # 隐藏标题
    legend.key.size = unit(12, 'pt'),  # 图例大小
    legend.text = element_text(size = 12),  # 图例文字字号
    legend.key.spacing.y = unit(5, 'pt'),  # 图例各项上下间距
    legend.background = element_blank(),  # 去掉图例背景色
    legend.key = element_blank()  # 去掉图例背景色
  ) +
  theme(  # xy轴标签和刻度标签字号
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  ) +
  theme(  # 图边距
    plot.margin = margin(r = 50, t = 20, b = 20, l = 20)
  );
# 画TMB
p2 <- ggplot(
  data2, 
  aes(x = cancer_type, y = tmb), 
) +
  geom_violin(
    aes(fill = response), 
    trim = FALSE,
    width = 1.1,
    position = position_dodge(0.9)
  ) +
  scale_fill_manual(values = c("#01B1BC", "#E8B900")) +
  scale_color_manual(values = c("black", "black")) +
  geom_boxplot(
    aes(color = response),
    width = 0.2,
    outlier.size = 3,
    fatten = 5,
    position = position_dodge(0.9),
    show_guide = FALSE
  ) +
  labs(
    x = "Cancer type", 
    y = substitute(
      paste(log[2], "(TMB+1)"),list(log = "log")
    )
  ) +
  scale_y_continuous(
      breaks = c(0, 3, 6),
      labels = c("0", "3", "6")
  ) +
  theme(
    panel.grid.major = element_line(colour = NA),
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.grid.minor = element_blank()
  ) +
  theme(
    panel.border = element_blank(), 
    axis.line = element_line()
  ) +
  theme(
    axis.ticks.x=element_blank()
  ) +
  theme(
    legend.position = c(1, 0.5),
    legend.title = element_blank(),
    legend.key.size = unit(12, 'pt'),
    legend.text = element_text(size = 12),
    legend.key.spacing.y = unit(5, 'pt'),
    legend.background = element_blank(),
    legend.key = element_blank()
  ) +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  ) +
  theme(
    plot.margin = margin(r = 50, t = 20, b = 20, l = 20)
  );
# 添加p值
draw_p <- function(p, pval, x, y){  # 在图上加p值
  change_p <- function(p){  # 改p值格式
    if(p>=0.01){  # 如果大于0.01就保留两位小数
      p <- round(as.numeric(p), 2);
      return(format(as.numeric(as.character(p)), scientific = F));
    }
    if(p>=0.001){  # 如果大于0.001就保留3位小数
      p <- round(as.numeric(p), 3);
      return(format(as.numeric(as.character(p)), scientific = F));
    }
    if(p>=0.0001){  # 如果大于0.0001就保留4位小数
      p <- round(as.numeric(p), 4);
      return(format(as.numeric(as.character(p)), scientific = F));
    }
    p <- format(as.numeric(as.character(p)), scientific = T)
    split_res <- strsplit(as.character(p), "e");
    front <- split_res[[1]][1];
    end <- split_res[[1]][2];
    front <- sprintf("%0.2f", as.numeric(front));
    if(substr(end, 2, 2) == '0') end <- gsub("0", "", end);
    res <- substitute(
      paste(front %*% ten^end),
      list(front = front, end = end, ten = 10));
    return(res);
  }
  ann <- substitute(paste(italic(P), " = ", pval), list(pval = change_p(pval)));
  p <- p +
  annotate(
    geom = "text",
    label = as.character(as.expression(ann)),
    x = as.numeric(x),
    y = as.numeric(y),
    hjust = 0,
    vjust = 1,
    parse = T,
    size = 6
  );
  return(p);
}
draw_p_multiple <- function(p, p_list, xpos, ypos){
  df <- data.frame(
    p = p_list,
    ypos = ypos,
    xpos = xpos
  );
  for(i in 1:nrow(df)){
    p <- draw_p(p, df[i, 1], i-df[i, 3], df[i, 2]);
  }
  return(p);
}
# RF16
p1_new <- draw_p_multiple(
  p1, data1_p, 
  c(0.3, 0.21, 0.29, 0.29),
  c(0.89, 0.91, 0.72, 0.73)
);
pdf(file = paste0("plot/RF16-Response-probability_violin-plot.pdf"), width = 12, height = 6);
print(p1_new);
dev.off();
# TMB
p2_new <- draw_p_multiple(
  p2, data2_p, 
  c(0.235, 0.18, 0.185, 0.175),
  c(8.7, 8.9, 8.4, 8.5)
);
pdf(file = paste0("plot/log2-TMB_violin-plot.pdf"), width = 12, height = 6);
print(p2_new);
dev.off();
```

